# Change these first
owner: thomasmerz # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Nextcloud
    url: $URL_NEXTCLOUD
    icon: $URL_NEXTCLOUD_ICO
  - name: Portainer-DE
    url: $URL_PORTAINER_DE
    icon: https://www.portainer.io/favicon.ico
  - name: Portainer-FI
    url: $URL_PORTAINER_FI
    icon: https://www.portainer.io/favicon.ico
    __dangerous__disable_verify_host: true
#  - name: Portainer-merz-nimbus
#    url: $URL_PORTAINER_MERZ_NIMBUS
#    icon: https://www.portainer.io/favicon.ico
#    __dangerous__disable_verify_host: true
  - name: Pihole-DE
    url: $URL_PIHOLE_DE
    icon: https://pi-hole.net/favicon.ico
  - name: Pihole-FI
    url: $URL_PIHOLE_FI
    icon: https://pi-hole.net/favicon.ico
#  - name: Pihole-merz-nimbus
#    url: $URL_PIHOLE_MERZ_NIMBUS
#    icon: https://pi-hole.net/favicon.ico
  - name: Syncthing-hetzner-cloudserver-DE
    url: $URL_SYNCTHING_HETZNER_CLOUDSERVER_DE
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
    __dangerous__insecure: true
  - name: Syncthing-hetzner-cloudserver-FI
    url: $URL_SYNCTHING_HETZNER_CLOUDSERVER_FI
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
    __dangerous__insecure: true
  - name: Syncthing-contabo-mo
    url: $URL_SYNCTHING_CONTABO_MO
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
    __dangerous__insecure: true
  - name: Syncthing-merz-nimbus-tm
    url: $URL_SYNCTING_MERZ_NIMBUS_TM
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
    __dangerous__insecure: true
  - name: Syncthing-merz-nimbus-bi
    url: $URL_SYNCTING_MERZ_NIMBUS_BI
    icon: https://syncthing.net/img/favicons/favicon-32x32.png
    __dangerous__insecure: true
#  - name: MCServer_jo
#    url: $URL_MCSERVER_JO
#  - name: MCServer_si
#    url: $URL_MCSERVER_SI
#  - name: MCServer_ga
#    url: $URL_MCSERVER_GA

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  ###cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
